on:
  workflow_dispatch:

jobs:
  funicular:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p win/art mac/art linux/art
          echo win > win/art/art.txt
          echo win > win/art/win.txt
          echo mac > mac/art/art.txt
          echo mac > mac/art/mac.txt
          echo linux > linux/art/art.txt
          echo linux > linux/art/linux.txt
      - uses: actions/upload-artifact@v4
        with:
          name: art-win
          path: win
      - uses: actions/upload-artifact@v4
        with:
          name: art-mac
          path: mac
      - uses: actions/upload-artifact@v4
        with:
          name: art-linux
          path: linux
      - uses: actions/download-artifact@v4
        with:
          pattern: art-*
          path: art
          merge-multiple: true
      - run: ls art
